version: "2"
services:
    web:
        build: .
        image: fring/apache
        volumes:
            - .:/var/www/fring
        ports:
            - "80:80"
    mysql:
        image: mysql:latest
        volumes:
            - /home/clayton/tmp/mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234 
