version: "2"
services:
    web:
        build: .
        image: fring/apache
        container_name: fring-web
        ports:
            - "8080:8080"
    mysql:
        image: mysql:latest
        container_name: fring-mysql
        volumes:
            - /home/clayton/tmp/mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234 
            - TZ=America/Cuiaba
