version: "2"
services:
    web:
        build: .
        image: fring/apache
        container_name: fring-web
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www/fring
            - ./httpd/wsgi.conf:/etc/httpd/conf.d/wsgi.conf
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        container_name: fring-mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234 
            - MYSQL_DATABASE=fring
            - MYSQL_USER=fring
            - MYSQL_PASSWORD=fring
            - TZ=America/Cuiaba

volumes:
    mysql-data:
