"""Added table to store more than one image per publication

Revision ID: 26850ac915a3
Revises: 
Create Date: 2017-11-29 19:30:04.713286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session

from core.publicacoes.models import Publicacao, ImagemPublicacao

Session = sessionmaker()

Base = declarative_base()

class PublicacaoAntiga(Base):
    __tablename__ = "publicacao"
    guid_publicacao = sa.Column(sa.String(36), primary_key=True)
    imagem          = sa.Column(sa.String(64))

# revision identifiers, used by Alembic.
revision = '26850ac915a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacao_imagem',
    sa.Column('guid_imagem', sa.String(length=36), nullable=False),
    sa.Column('guid_publicacao', sa.String(length=36), nullable=False),
    sa.Column('caminho', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['guid_publicacao'], ['publicacao.guid_publicacao'], ),
    sa.PrimaryKeyConstraint('guid_imagem')
    )

    bind = op.get_bind()
    session = Session(bind=bind)

    for publicacao in session.query(PublicacaoAntiga):
        imagem = ImagemPublicacao()
        imagem.guid_imagem = 'abcd1234'
        imagem.guid_publicacao = publicacao.guid_publicacao
        imagem.caminho = publicacao.imagem
        session.add(imagem)

    session.commit()

    op.drop_column(u'publicacao', 'imagem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'publicacao', sa.Column('imagem', mysql.VARCHAR(length=64), nullable=True))
    op.drop_table('publicacao_imagem')
    # ### end Alembic commands ###
